version: 2
updates:
  # Golangの依存関係管理（バックエンド用）
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    # 更新の設定
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Node.js（Nuxt.js/Vue）の依存関係管理（フロントエンド用）
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    # 更新の設定
    allow:
      - dependency-type: "all"
