# 軽量なベースイメージを使用
FROM golang:1.22.1-bullseye

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y \
    git \
    make \
    curl \
    && rm -rf /var/lib/apt/lists/*

# golangci-lintのインストール
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

# 作業ディレクトリを設定
WORKDIR /usr/src/app

# go.modとgo.sumのコピーは不要（volumeでマウントされるため）

# Airをグローバルにインストール
RUN go install github.com/cosmtrek/air@v1.42.0

# Airでアプリケーションを起動
CMD ["air", "-c", ".air.toml"]