basePath: /
definitions:
  dto.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponse:
    properties:
      display_name:
        description: UI表示用
        type: string
      id:
        type: string
    type: object
  dto.RegisterUserRequest:
    properties:
      display_name:
        example: John Doe
        maxLength: 100
        minLength: 1
        type: string
      email:
        example: user@example.com
        type: string
      password:
        example: password
        maxLength: 32
        minLength: 8
        type: string
    required:
    - display_name
    - email
    - password
    type: object
  dto.RegisterUserResponse:
    properties:
      created_at:
        type: string
      display_name:
        description: UI表示用
        type: string
      id:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      error:
        example: error message
        type: string
    type: object
host: localhost:8088
info:
  contact: {}
  description: This is Markdown Blog API
  title: Markdown Blog API
  version: "1.0"
paths:
  /api/users/login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Login user
      tags:
      - users
  /api/users/logout:
    post:
      consumes:
      - application/json
      description: Logout current user and invalidate session
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - CookieAuth: []
      summary: Logout user
      tags:
      - users
  /api/users/register:
    post:
      consumes:
      - application/json
      description: Register a new user with email, password and display name
      parameters:
      - description: User registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.RegisterUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Register a new user
      tags:
      - users
securityDefinitions:
  CookieAuth:
    in: cookie
    name: session_token
    type: apiKey
swagger: "2.0"
