name: SonarCloud Analysis
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 全履歴を取得（より正確な解析のため）

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=riii111
            -Dsonar.projectKey=riii111_MarkdownBlog
            -Dsonar.sources=frontend,backend
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
            -Dsonar.go.coverage.reportPaths=backend/coverage.out
